### ISSUE TITLE
Using the Box component failed to extend tag with 'withComponent' but works with the Grid Component

### ISSUE THREAD

**Issue by madiodio** [jxnblk/grid-styled#23]
First of all, thanks for this awesome tool 👍.

I was trying to use the `Box` component to extend the tag with the `withComponent` helper provided by styled-components like this: 
```
const MyComp = Box.withComponent('li');
```
but I got the error  `_gridStyled.Box.withComponent is not a function`

So I'm confused because it works correctly when `Grid` is used instead of `Box` or even the `Flex` one.
Is there something I'm missing. Thanks for your help!

**Comment by jxnblk** [comment]
I think it has to do with wrapping the Box component with the HOC here: https://github.com/jxnblk/grid-styled/blob/master/src/Box.js#L6

I've had issues trying to use the `.withComponent()` method in styled-components, and I think it gets lost when a styled-component is used to render a normal React component. I think the solution here is to pass the HOC-wrapped component to the `styled` function (e.g. `const Box = styled(hoc('div'))`) but I haven't taken the time to test this yet

**Comment by madiodio** [comment]
Yes, That's exactly the HOC that's causing the issue. And since styled-components expects a component I don't think this `const Box = styled(hoc('div'))` will work either. I will try to dug into the code if there would be another way to stop that attribute from getting passed down to props hopefully won't encounter the React `Unknown Prop` Warning

**Comment by jxnblk** [comment]
This discussion is relevant to the issue caused here https://github.com/styled-components/styled-components/issues/439

**Comment by jxnblk** [comment]
I've removed the `hoc` from Box – in the hopes that styled-components moves away from the whitelist approach in the near future – which should allow `.withComponent()` to work with `2.0.0-8` and up. If you'd like to avoid passing `width` to DOM elements, you can use the `w` prop as an alias
